blank_issues_enabled: true
contact_links:
  - name: Do you want to discuss EIP ideas or ask questions about the process?
    url: https://ethereum-magicians.org/
    about: Use the Fellowship of Ethereum Magicians for EIP-related discussion!
  - name: Consistency in Style and Terminology
    url: https://github.com/ethereum/EIPs/blob/master/.github/CONTRIBUTING.md#consistency-in-style-and-terminology
    about: Ensure consistency in style and terminology throughout the documentation.
  - name: Continuous Improvement
    url: https://github.com/ethereum/EIPs/blob/master/.github/CONTRIBUTING.md#continuous-improvement
    about: Encourage feedback and continuous improvement of the documentation.
