on:
  schedule:
    # A job that runs every sunday at 00:00
    - cron:  '0 0 * * 0'
  workflow_dispatch:

name: Auto Stagnate Bot
jobs:
  auto_stagnate_bot:
    if: github.repository == 'ethereum/eips'
    runs-on: ubuntu-latest
    name: Auto Stagnate Bot
    steps:
      - name: Checkout
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f
      - name: Setup Node.js Environment
        uses: actions/setup-node@d98fa1113850e562f83c7fc3a89c0ecd7a87fbed
        with:
          node-version: '14'
      - name: auto-stagnate-bot
        uses: ethereum/EIP-Bot@b3ac0ba3600aea27157fc68d1e36c08cc5a6db77 # mark-eips-stale
        id: auto-stagnate-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
